language: c

sudo: required

before_script: ./Tools/scripts/setupPrereqs.sh

script: ./Tools/scripts/buildGimbalFirmware.sh

addons:
  artifacts: true

notifications:
  slack: 3dr:OTjxfq1oqdWi9plQnvEhmksZ