#ifndef MAVLINK_BOOTLOADER_H_
#define MAVLINK_BOOTLOADER_H_

void MAVLINK_Flash();


#define BOOTLOADER_VERSION_MAJOR	0x03
#define BOOTLOADER_VERSION_MINOR	0x00
#define BOOTLOADER_VERSION			((BOOTLOADER_VERSION_MAJOR << 8) | BOOTLOADER_VERSION_MINOR)

extern unsigned char buffer[];

#endif /* MAVLINK_BOOTLOADER_H_ */
