#ifndef MAVLINK_BOOTLOADER_H_
#define MAVLINK_BOOTLOADER_H_

Uint32 MAVLINK_Flash();


#define BOOTLOADER_VERSION_MAJOR	0x02
#define BOOTLOADER_VERSION_MINOR	0x07
#define BOOTLOADER_VERSION			((BOOTLOADER_VERSION_MAJOR << 8) | BOOTLOADER_VERSION_MINOR)

extern unsigned char buffer[];

#endif /* MAVLINK_BOOTLOADER_H_ */
